import CodeRoundedIcon from "@mui/icons-material/CodeRounded";
import LocationOnOutlinedIcon from "@mui/icons-material/LocationOnOutlined";
import SendRoundedIcon from "@mui/icons-material/SendRounded";
import TerminalRoundedIcon from "@mui/icons-material/TerminalRounded";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import ProjectCard from "../components/ProjectCard";
import { usePortfolioStore } from "../stores/portfolioStore";
import { ui } from "../styles";

const timeline = [["2019","High school","Completed high school and began preparing for a future in technology."],["2022","Computer University, Myeik","Started a Computer Science degree and built a stronger technical foundation."],["2023","Web foundations","Studied core web development at Hornbill Information Technology."],["2024","Frontend specialization","Focused on modern JavaScript and React at MMSIT."],["Now","Full-stack growth","Building with Node.js, MongoDB, and production-minded workflows."]];
const endpoints = [
  {method:"GET",path:"/api/v1/profile",status:"200 OK",response:{status:200,data:{name:"Zarni Maung",role:"Junior Full Stack Web Developer",location:"Myeik, Myanmar"}}},
  {method:"GET",path:"/api/v1/skills",status:"200 OK",response:{status:200,data:{frontend:["React","JavaScript","Tailwind CSS"],backend:["Node.js","Express.js","PHP"]}}},
  {method:"POST",path:"/api/v1/contact",status:"201 Created",response:{status:201,message:"Contact request created",data:{responseTime:"24 hours"}}},
];
const categories = ["all","frontend","backend","database","tools"];
const label = "inline-flex w-fit items-center gap-2 rounded-lg border-[3px] border-black bg-[#FFE66D] px-3 py-2 text-xs font-black uppercase tracking-[.14em] shadow-[4px_4px_0_#000]";

export default function Home() {
  const { person, skills, projects, services } = usePortfolioStore();
  const [category,setCategory] = useState("all");
  const [endpoint,setEndpoint] = useState(endpoints[0]);
  const [response,setResponse] = useState(false);
  const [requests,setRequests] = useState(0);
  const visibleSkills = useMemo(() => category === "all" ? Object.values(skills).flat() : skills[category] ?? [], [category,skills]);
  return <div>
    <section className="grid min-h-[calc(100vh-76px)] items-center gap-8 py-10 lg:grid-cols-[1.15fr_.85fr] lg:py-16">
      <div className="relative z-10"><p className={`${label} mb-7 -rotate-1 bg-[#A3E635]`}><LocationOnOutlinedIcon fontSize="small"/>{person.location}</p><h1 className={ui.h1}>I build useful<br/><span className="inline-block -rotate-1 rounded-2xl border-[4px] border-black bg-[#67E8F9] px-3 pb-2 shadow-[8px_8px_0_#000]">digital things.</span></h1><p className="mt-8 max-w-2xl text-lg font-bold leading-8 text-black/70 md:text-xl">Junior full-stack developer turning complex ideas into clear, responsive products with thoughtful details.</p><div className="mt-8 flex flex-wrap gap-4"><Link to="/projects" className={`${ui.button} ${ui.primaryButton}`}>Explore my work</Link><a href="/Zarni_Maung_CV.pdf" target="_blank" rel="noopener noreferrer" className={`${ui.button} ${ui.secondaryButton}`}>View résumé</a></div><div className="mt-10 flex flex-wrap gap-3">{person.highlights.slice(0,3).map((item)=><span key={item} className={ui.stackItem}>{item}</span>)}</div></div>
      <aside className="relative mx-auto w-full max-w-[500px] lg:rotate-1"><div className="absolute -inset-3 translate-x-2 translate-y-2 rounded-[22px] border-[3px] border-black bg-[#FB923C]"/><div className="relative overflow-hidden rounded-[22px] border-[4px] border-black bg-[#FB7185] p-4 shadow-[10px_10px_0_#000]"><div className="relative overflow-hidden rounded-2xl border-[3px] border-black bg-[#FFE66D]"><img src={person.photo} alt={`${person.name}, ${person.title}`} className="aspect-[4/4.4] w-full object-cover object-top"/><span className="absolute bottom-4 left-4 rounded-lg border-[3px] border-black bg-white px-3 py-2 text-sm font-black shadow-[4px_4px_0_#000]">Available for opportunities</span></div><div className="mt-4 flex items-center justify-between gap-4 rounded-xl border-[3px] border-black bg-white p-4"><div><p className="font-black">{person.name}</p><p className="text-sm font-bold text-black/60">{person.title}</p></div><span className="h-4 w-4 rounded-full border-2 border-black bg-[#A3E635]"/></div></div></aside>
    </section>
    <section id="skills" className={`${ui.section} border-y-[3px] border-black bg-[#67E8F9] px-5`}><div className={ui.sectionHeading}><p className={label}>01 / Toolkit</p><div className={ui.sectionHeadingContent}><h2 className={ui.h2}>The tools behind<br/>the outcome.</h2><p className="max-w-md font-bold leading-7">A practical stack for responsive interfaces, reliable APIs, and complete web experiences.</p></div></div><div role="tablist" aria-label="Skill categories" className="mb-8 flex flex-wrap gap-3">{categories.map((item)=><button key={item} role="tab" aria-selected={category===item} onClick={()=>setCategory(item)} className={`${ui.raised} min-h-11 px-4 text-sm font-black capitalize ${category===item?"translate-x-1 translate-y-1 bg-[#A3E635] shadow-[2px_2px_0_#000]":"bg-white"}`}>{item}</button>)}</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{visibleSkills.map((skill,index)=><div key={skill} className={`rounded-2xl border-[3px] border-black p-4 shadow-[5px_5px_0_#000] transition-transform hover:-translate-y-1 ${index%3===0?"bg-[#FFE66D]":index%3===1?"bg-white":"bg-[#FB7185]"}`}><span className="mb-6 grid h-10 w-10 place-items-center rounded-lg border-2 border-black bg-black text-xs font-black text-white">{skill.slice(0,2).toUpperCase()}</span><p className="break-words text-sm font-black">{skill}</p></div>)}</div></section>
    <section className={ui.section}><div className={ui.sectionHeading}><p className={`${label} bg-[#FB7185]`}>02 / Selected work</p><div className={ui.sectionHeadingContent}><h2 className={ui.h2}>Built to solve,<br/>not just impress.</h2><Link to="/projects" className={`${ui.button} ${ui.secondaryButton}`}>See all projects</Link></div></div><div className="grid gap-7 lg:grid-cols-3">{projects.slice(0,3).map((project,index)=><ProjectCard key={project.id} project={project} bgColor={["bg-[#FFE66D]","bg-[#67E8F9]","bg-[#FB7185]"][index]}/>)}</div></section>
    <section className={`${ui.section} border-y-[3px] border-black bg-[#FFE66D] px-5`}><div className={ui.sectionHeading}><p className={`${label} bg-white`}>03 / What I do</p><h2 className={ui.h2}>From first screen<br/>to shipped product.</h2></div><div className="grid gap-5 md:grid-cols-3">{services.map((service,index)=><article key={service.label} className={`rounded-[18px] border-[3px] border-black p-6 shadow-[7px_7px_0_#000] ${["bg-[#67E8F9]","bg-[#FB7185]","bg-[#A3E635]"][index%3]}`}><span className="mb-10 grid h-12 w-12 place-items-center rounded-xl border-[3px] border-black bg-white text-xl font-black">0{index+1}</span><h3 className="text-2xl font-black">{service.label}</h3><p className="mt-3 font-bold leading-7 text-black/70">{service.description}</p></article>)}</div></section>
    <section className={ui.section}><div className={ui.sectionHeading}><p className={`${label} bg-[#FB923C]`}>04 / Journey</p><h2 className={ui.h2}>Always learning.<br/>Always building.</h2></div><ol className="grid gap-4">{timeline.map(([year,title,description],index)=><li key={year} className="grid gap-4 rounded-[18px] border-[3px] border-black bg-white p-5 shadow-[6px_6px_0_#000] md:grid-cols-[110px_1fr]"><span className={`h-fit w-fit rounded-lg border-2 border-black px-3 py-1 text-sm font-black ${index%2?"bg-[#67E8F9]":"bg-[#FFE66D]"}`}>{year}</span><div><h3 className="text-xl font-black">{title}</h3><p className="mt-2 font-semibold leading-7 text-black/65">{description}</p></div></li>)}</ol></section>
    <section className={`${ui.section} border-y-[3px] border-black bg-[#A3E635] px-5`}><div className={ui.sectionHeading}><p className={`${label} bg-white`}><TerminalRoundedIcon fontSize="small"/>05 / Playground</p><div className={ui.sectionHeadingContent}><h2 className={ui.h2}>Try the portfolio<br/>as an API.</h2><span className="rounded-lg border-[3px] border-black bg-[#FB7185] px-4 py-2 font-black shadow-[4px_4px_0_#000]">{requests} requests sent</span></div></div><div className="overflow-hidden rounded-[20px] border-[3px] border-black bg-white shadow-[9px_9px_0_#000]"><div className="flex justify-between border-b-[3px] border-black bg-black p-4 text-white"><span className="flex gap-2"><i className="h-3 w-3 rounded-full bg-[#FB7185]"/><i className="h-3 w-3 rounded-full bg-[#FFE66D]"/><i className="h-3 w-3 rounded-full bg-[#A3E635]"/></span><code className="text-xs text-[#67E8F9]">api.zarni.dev</code></div><div className="grid lg:grid-cols-2"><div className="grid gap-6 border-b-[3px] border-black p-5 lg:border-b-0 lg:border-r-[3px] lg:p-7"><div className="grid gap-2">{endpoints.map((item)=><button key={item.path} onClick={()=>{setEndpoint(item);setResponse(false)}} className={`${ui.raised} flex min-h-12 items-center gap-3 px-3 text-left text-xs font-black ${endpoint.path===item.path?"bg-[#67E8F9]":"bg-white"}`}><span className="rounded border-2 border-black bg-[#A3E635] px-2 py-1">{item.method}</span><code>{item.path}</code></button>)}</div><button onClick={()=>{setRequests(v=>v+1);setResponse(true)}} className={`${ui.button} ${ui.extraButton} w-full`}><SendRoundedIcon fontSize="small"/>{response?"Send again":"Send request"}</button></div><div className="p-5 lg:p-7"><div className="mb-3 flex justify-between"><p className="text-xs font-black uppercase">Response</p><span className="rounded border-2 border-black bg-[#A3E635] px-2 py-1 text-xs font-black">{endpoint.status}</span></div>{response?<pre aria-live="polite" className="min-h-72 overflow-auto rounded-xl border-[3px] border-black bg-black p-5 text-sm font-bold leading-6 text-[#A3E635]">{JSON.stringify(endpoint.response,null,2)}</pre>:<div className="grid min-h-72 place-items-center rounded-xl border-[3px] border-dashed border-black bg-[#fffdf5] p-6 text-center"><div><CodeRoundedIcon fontSize="large"/><p className="mt-3 text-xl font-black">Ready when you are.</p><p className="mt-2 text-sm font-bold text-black/55">Select an endpoint and send the request.</p></div></div>}</div></div></div></section>
  </div>;
}
